/* This file was generated by SableCC (http://www.sablecc.org/). */

package mangaba.node;

import mangaba.analysis.*;

@SuppressWarnings("nls")
public final class ABooleanoTipo extends PTipo
{
    private TNBooleano _nBooleano_;

    public ABooleanoTipo()
    {
        // Constructor
    }

    public ABooleanoTipo(
        @SuppressWarnings("hiding") TNBooleano _nBooleano_)
    {
        // Constructor
        setNBooleano(_nBooleano_);

    }

    @Override
    public Object clone()
    {
        return new ABooleanoTipo(
            cloneNode(this._nBooleano_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABooleanoTipo(this);
    }

    public TNBooleano getNBooleano()
    {
        return this._nBooleano_;
    }

    public void setNBooleano(TNBooleano node)
    {
        if(this._nBooleano_ != null)
        {
            this._nBooleano_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._nBooleano_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._nBooleano_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._nBooleano_ == child)
        {
            this._nBooleano_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._nBooleano_ == oldChild)
        {
            setNBooleano((TNBooleano) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
