/* This file was generated by SableCC (http://www.sablecc.org/). */

package mangaba.node;

import mangaba.analysis.*;

@SuppressWarnings("nls")
public final class ACaractereTipo extends PTipo
{
    private TNCaract _nCaract_;

    public ACaractereTipo()
    {
        // Constructor
    }

    public ACaractereTipo(
        @SuppressWarnings("hiding") TNCaract _nCaract_)
    {
        // Constructor
        setNCaract(_nCaract_);

    }

    @Override
    public Object clone()
    {
        return new ACaractereTipo(
            cloneNode(this._nCaract_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACaractereTipo(this);
    }

    public TNCaract getNCaract()
    {
        return this._nCaract_;
    }

    public void setNCaract(TNCaract node)
    {
        if(this._nCaract_ != null)
        {
            this._nCaract_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._nCaract_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._nCaract_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._nCaract_ == child)
        {
            this._nCaract_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._nCaract_ == oldChild)
        {
            setNCaract((TNCaract) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
