/* This file was generated by SableCC (http://www.sablecc.org/). */

package mangaba.node;

import mangaba.analysis.*;

@SuppressWarnings("nls")
public final class AFuncaoAtribuicoes extends PAtribuicoes
{
    private PVariavel _variavel_;
    private PFuncaoChamada _funcaoChamada_;

    public AFuncaoAtribuicoes()
    {
        // Constructor
    }

    public AFuncaoAtribuicoes(
        @SuppressWarnings("hiding") PVariavel _variavel_,
        @SuppressWarnings("hiding") PFuncaoChamada _funcaoChamada_)
    {
        // Constructor
        setVariavel(_variavel_);

        setFuncaoChamada(_funcaoChamada_);

    }

    @Override
    public Object clone()
    {
        return new AFuncaoAtribuicoes(
            cloneNode(this._variavel_),
            cloneNode(this._funcaoChamada_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFuncaoAtribuicoes(this);
    }

    public PVariavel getVariavel()
    {
        return this._variavel_;
    }

    public void setVariavel(PVariavel node)
    {
        if(this._variavel_ != null)
        {
            this._variavel_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._variavel_ = node;
    }

    public PFuncaoChamada getFuncaoChamada()
    {
        return this._funcaoChamada_;
    }

    public void setFuncaoChamada(PFuncaoChamada node)
    {
        if(this._funcaoChamada_ != null)
        {
            this._funcaoChamada_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._funcaoChamada_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._variavel_)
            + toString(this._funcaoChamada_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._variavel_ == child)
        {
            this._variavel_ = null;
            return;
        }

        if(this._funcaoChamada_ == child)
        {
            this._funcaoChamada_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._variavel_ == oldChild)
        {
            setVariavel((PVariavel) newChild);
            return;
        }

        if(this._funcaoChamada_ == oldChild)
        {
            setFuncaoChamada((PFuncaoChamada) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
