/* This file was generated by SableCC (http://www.sablecc.org/). */

package mangaba.node;

import mangaba.analysis.*;

@SuppressWarnings("nls")
public final class AFuncaoChamada extends PFuncaoChamada
{
    private TIdentificador _identificador_;
    private PBlocoExpr _blocoExpr_;

    public AFuncaoChamada()
    {
        // Constructor
    }

    public AFuncaoChamada(
        @SuppressWarnings("hiding") TIdentificador _identificador_,
        @SuppressWarnings("hiding") PBlocoExpr _blocoExpr_)
    {
        // Constructor
        setIdentificador(_identificador_);

        setBlocoExpr(_blocoExpr_);

    }

    @Override
    public Object clone()
    {
        return new AFuncaoChamada(
            cloneNode(this._identificador_),
            cloneNode(this._blocoExpr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFuncaoChamada(this);
    }

    public TIdentificador getIdentificador()
    {
        return this._identificador_;
    }

    public void setIdentificador(TIdentificador node)
    {
        if(this._identificador_ != null)
        {
            this._identificador_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._identificador_ = node;
    }

    public PBlocoExpr getBlocoExpr()
    {
        return this._blocoExpr_;
    }

    public void setBlocoExpr(PBlocoExpr node)
    {
        if(this._blocoExpr_ != null)
        {
            this._blocoExpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._blocoExpr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._identificador_)
            + toString(this._blocoExpr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._identificador_ == child)
        {
            this._identificador_ = null;
            return;
        }

        if(this._blocoExpr_ == child)
        {
            this._blocoExpr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._identificador_ == oldChild)
        {
            setIdentificador((TIdentificador) newChild);
            return;
        }

        if(this._blocoExpr_ == oldChild)
        {
            setBlocoExpr((PBlocoExpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
