/* This file was generated by SableCC (http://www.sablecc.org/). */

package mangaba.node;

import mangaba.analysis.*;

@SuppressWarnings("nls")
public final class AFuncaoComando extends PComando
{
    private PFuncaoChamada _funcaoChamada_;

    public AFuncaoComando()
    {
        // Constructor
    }

    public AFuncaoComando(
        @SuppressWarnings("hiding") PFuncaoChamada _funcaoChamada_)
    {
        // Constructor
        setFuncaoChamada(_funcaoChamada_);

    }

    @Override
    public Object clone()
    {
        return new AFuncaoComando(
            cloneNode(this._funcaoChamada_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFuncaoComando(this);
    }

    public PFuncaoChamada getFuncaoChamada()
    {
        return this._funcaoChamada_;
    }

    public void setFuncaoChamada(PFuncaoChamada node)
    {
        if(this._funcaoChamada_ != null)
        {
            this._funcaoChamada_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._funcaoChamada_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._funcaoChamada_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._funcaoChamada_ == child)
        {
            this._funcaoChamada_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._funcaoChamada_ == oldChild)
        {
            setFuncaoChamada((PFuncaoChamada) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
