/* This file was generated by SableCC (http://www.sablecc.org/). */

package mangaba.node;

import mangaba.analysis.*;

@SuppressWarnings("nls")
public final class AFuncaoBlocoFuncoes extends PBlocoFuncoes
{
    private PFuncao _funcao_;

    public AFuncaoBlocoFuncoes()
    {
        // Constructor
    }

    public AFuncaoBlocoFuncoes(
        @SuppressWarnings("hiding") PFuncao _funcao_)
    {
        // Constructor
        setFuncao(_funcao_);

    }

    @Override
    public Object clone()
    {
        return new AFuncaoBlocoFuncoes(
            cloneNode(this._funcao_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFuncaoBlocoFuncoes(this);
    }

    public PFuncao getFuncao()
    {
        return this._funcao_;
    }

    public void setFuncao(PFuncao node)
    {
        if(this._funcao_ != null)
        {
            this._funcao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._funcao_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._funcao_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._funcao_ == child)
        {
            this._funcao_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._funcao_ == oldChild)
        {
            setFuncao((PFuncao) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
