/* This file was generated by SableCC (http://www.sablecc.org/). */

package mangaba.node;

import mangaba.analysis.*;

@SuppressWarnings("nls")
public final class ANaoExprLogica extends PExprLogica
{
    private PExprLogica _l_;

    public ANaoExprLogica()
    {
        // Constructor
    }

    public ANaoExprLogica(
        @SuppressWarnings("hiding") PExprLogica _l_)
    {
        // Constructor
        setL(_l_);

    }

    @Override
    public Object clone()
    {
        return new ANaoExprLogica(
            cloneNode(this._l_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANaoExprLogica(this);
    }

    public PExprLogica getL()
    {
        return this._l_;
    }

    public void setL(PExprLogica node)
    {
        if(this._l_ != null)
        {
            this._l_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._l_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._l_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._l_ == child)
        {
            this._l_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._l_ == oldChild)
        {
            setL((PExprLogica) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
