/* This file was generated by SableCC (http://www.sablecc.org/). */

package mangaba.node;

import mangaba.analysis.*;

@SuppressWarnings("nls")
public final class AParaCadaComando extends PComando
{
    private PParacadaEstrutura _paracadaEstrutura_;

    public AParaCadaComando()
    {
        // Constructor
    }

    public AParaCadaComando(
        @SuppressWarnings("hiding") PParacadaEstrutura _paracadaEstrutura_)
    {
        // Constructor
        setParacadaEstrutura(_paracadaEstrutura_);

    }

    @Override
    public Object clone()
    {
        return new AParaCadaComando(
            cloneNode(this._paracadaEstrutura_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAParaCadaComando(this);
    }

    public PParacadaEstrutura getParacadaEstrutura()
    {
        return this._paracadaEstrutura_;
    }

    public void setParacadaEstrutura(PParacadaEstrutura node)
    {
        if(this._paracadaEstrutura_ != null)
        {
            this._paracadaEstrutura_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._paracadaEstrutura_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._paracadaEstrutura_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._paracadaEstrutura_ == child)
        {
            this._paracadaEstrutura_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._paracadaEstrutura_ == oldChild)
        {
            setParacadaEstrutura((PParacadaEstrutura) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
