/* This file was generated by SableCC (http://www.sablecc.org/). */

package mangaba.node;

import mangaba.analysis.*;

@SuppressWarnings("nls")
public final class AParaComando extends PComando
{
    private PParaEstrutura _paraEstrutura_;

    public AParaComando()
    {
        // Constructor
    }

    public AParaComando(
        @SuppressWarnings("hiding") PParaEstrutura _paraEstrutura_)
    {
        // Constructor
        setParaEstrutura(_paraEstrutura_);

    }

    @Override
    public Object clone()
    {
        return new AParaComando(
            cloneNode(this._paraEstrutura_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAParaComando(this);
    }

    public PParaEstrutura getParaEstrutura()
    {
        return this._paraEstrutura_;
    }

    public void setParaEstrutura(PParaEstrutura node)
    {
        if(this._paraEstrutura_ != null)
        {
            this._paraEstrutura_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._paraEstrutura_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._paraEstrutura_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._paraEstrutura_ == child)
        {
            this._paraEstrutura_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._paraEstrutura_ == oldChild)
        {
            setParaEstrutura((PParaEstrutura) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
