/* This file was generated by SableCC (http://www.sablecc.org/). */

package mangaba.node;

import mangaba.analysis.*;

@SuppressWarnings("nls")
public final class AParaEstrutura extends PParaEstrutura
{
    private PParaStant _paraStant_;

    public AParaEstrutura()
    {
        // Constructor
    }

    public AParaEstrutura(
        @SuppressWarnings("hiding") PParaStant _paraStant_)
    {
        // Constructor
        setParaStant(_paraStant_);

    }

    @Override
    public Object clone()
    {
        return new AParaEstrutura(
            cloneNode(this._paraStant_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAParaEstrutura(this);
    }

    public PParaStant getParaStant()
    {
        return this._paraStant_;
    }

    public void setParaStant(PParaStant node)
    {
        if(this._paraStant_ != null)
        {
            this._paraStant_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._paraStant_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._paraStant_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._paraStant_ == child)
        {
            this._paraStant_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._paraStant_ == oldChild)
        {
            setParaStant((PParaStant) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
