/* This file was generated by SableCC (http://www.sablecc.org/). */

package mangaba.node;

import mangaba.analysis.*;

@SuppressWarnings("nls")
public final class AParaStant2 extends PParaStant2
{
    private PParaStant3 _paraStant3_;

    public AParaStant2()
    {
        // Constructor
    }

    public AParaStant2(
        @SuppressWarnings("hiding") PParaStant3 _paraStant3_)
    {
        // Constructor
        setParaStant3(_paraStant3_);

    }

    @Override
    public Object clone()
    {
        return new AParaStant2(
            cloneNode(this._paraStant3_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAParaStant2(this);
    }

    public PParaStant3 getParaStant3()
    {
        return this._paraStant3_;
    }

    public void setParaStant3(PParaStant3 node)
    {
        if(this._paraStant3_ != null)
        {
            this._paraStant3_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._paraStant3_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._paraStant3_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._paraStant3_ == child)
        {
            this._paraStant3_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._paraStant3_ == oldChild)
        {
            setParaStant3((PParaStant3) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
