/* This file was generated by SableCC (http://www.sablecc.org/). */

package mangaba.node;

import mangaba.analysis.*;

@SuppressWarnings("nls")
public final class ASeSenaoComando extends PComando
{
    private PSenaoEstrutura _senaoEstrutura_;

    public ASeSenaoComando()
    {
        // Constructor
    }

    public ASeSenaoComando(
        @SuppressWarnings("hiding") PSenaoEstrutura _senaoEstrutura_)
    {
        // Constructor
        setSenaoEstrutura(_senaoEstrutura_);

    }

    @Override
    public Object clone()
    {
        return new ASeSenaoComando(
            cloneNode(this._senaoEstrutura_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASeSenaoComando(this);
    }

    public PSenaoEstrutura getSenaoEstrutura()
    {
        return this._senaoEstrutura_;
    }

    public void setSenaoEstrutura(PSenaoEstrutura node)
    {
        if(this._senaoEstrutura_ != null)
        {
            this._senaoEstrutura_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._senaoEstrutura_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._senaoEstrutura_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._senaoEstrutura_ == child)
        {
            this._senaoEstrutura_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._senaoEstrutura_ == oldChild)
        {
            setSenaoEstrutura((PSenaoEstrutura) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
