/* This file was generated by SableCC (http://www.sablecc.org/). */

package mangaba.node;

import java.util.*;
import mangaba.analysis.*;

@SuppressWarnings("nls")
public final class ASeStant extends PSeStant
{
    private PExprLogica _exprLogica_;
    private final LinkedList<PComando> _blocoComando_ = new LinkedList<PComando>();

    public ASeStant()
    {
        // Constructor
    }

    public ASeStant(
        @SuppressWarnings("hiding") PExprLogica _exprLogica_,
        @SuppressWarnings("hiding") List<?> _blocoComando_)
    {
        // Constructor
        setExprLogica(_exprLogica_);

        setBlocoComando(_blocoComando_);

    }

    @Override
    public Object clone()
    {
        return new ASeStant(
            cloneNode(this._exprLogica_),
            cloneList(this._blocoComando_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASeStant(this);
    }

    public PExprLogica getExprLogica()
    {
        return this._exprLogica_;
    }

    public void setExprLogica(PExprLogica node)
    {
        if(this._exprLogica_ != null)
        {
            this._exprLogica_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exprLogica_ = node;
    }

    public LinkedList<PComando> getBlocoComando()
    {
        return this._blocoComando_;
    }

    public void setBlocoComando(List<?> list)
    {
        for(PComando e : this._blocoComando_)
        {
            e.parent(null);
        }
        this._blocoComando_.clear();

        for(Object obj_e : list)
        {
            PComando e = (PComando) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._blocoComando_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exprLogica_)
            + toString(this._blocoComando_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exprLogica_ == child)
        {
            this._exprLogica_ = null;
            return;
        }

        if(this._blocoComando_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exprLogica_ == oldChild)
        {
            setExprLogica((PExprLogica) newChild);
            return;
        }

        for(ListIterator<PComando> i = this._blocoComando_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PComando) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
