/* This file was generated by SableCC (http://www.sablecc.org/). */

package mangaba.node;

import mangaba.analysis.*;

@SuppressWarnings("nls")
public final class AVariaveisBlocoVariaveis extends PBlocoVariaveis
{
    private PBlocoVariaveis _blocoVariaveis_;
    private PVariavel _variavel_;

    public AVariaveisBlocoVariaveis()
    {
        // Constructor
    }

    public AVariaveisBlocoVariaveis(
        @SuppressWarnings("hiding") PBlocoVariaveis _blocoVariaveis_,
        @SuppressWarnings("hiding") PVariavel _variavel_)
    {
        // Constructor
        setBlocoVariaveis(_blocoVariaveis_);

        setVariavel(_variavel_);

    }

    @Override
    public Object clone()
    {
        return new AVariaveisBlocoVariaveis(
            cloneNode(this._blocoVariaveis_),
            cloneNode(this._variavel_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVariaveisBlocoVariaveis(this);
    }

    public PBlocoVariaveis getBlocoVariaveis()
    {
        return this._blocoVariaveis_;
    }

    public void setBlocoVariaveis(PBlocoVariaveis node)
    {
        if(this._blocoVariaveis_ != null)
        {
            this._blocoVariaveis_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._blocoVariaveis_ = node;
    }

    public PVariavel getVariavel()
    {
        return this._variavel_;
    }

    public void setVariavel(PVariavel node)
    {
        if(this._variavel_ != null)
        {
            this._variavel_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._variavel_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._blocoVariaveis_)
            + toString(this._variavel_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._blocoVariaveis_ == child)
        {
            this._blocoVariaveis_ = null;
            return;
        }

        if(this._variavel_ == child)
        {
            this._variavel_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._blocoVariaveis_ == oldChild)
        {
            setBlocoVariaveis((PBlocoVariaveis) newChild);
            return;
        }

        if(this._variavel_ == oldChild)
        {
            setVariavel((PVariavel) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
