/* This file was generated by SableCC (http://www.sablecc.org/). */

package mangaba.node;

import mangaba.analysis.*;

@SuppressWarnings("nls")
public final class AVariasBlocoFuncoes extends PBlocoFuncoes
{
    private PBlocoFuncoes _blocoFuncoes_;
    private PFuncao _funcao_;

    public AVariasBlocoFuncoes()
    {
        // Constructor
    }

    public AVariasBlocoFuncoes(
        @SuppressWarnings("hiding") PBlocoFuncoes _blocoFuncoes_,
        @SuppressWarnings("hiding") PFuncao _funcao_)
    {
        // Constructor
        setBlocoFuncoes(_blocoFuncoes_);

        setFuncao(_funcao_);

    }

    @Override
    public Object clone()
    {
        return new AVariasBlocoFuncoes(
            cloneNode(this._blocoFuncoes_),
            cloneNode(this._funcao_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVariasBlocoFuncoes(this);
    }

    public PBlocoFuncoes getBlocoFuncoes()
    {
        return this._blocoFuncoes_;
    }

    public void setBlocoFuncoes(PBlocoFuncoes node)
    {
        if(this._blocoFuncoes_ != null)
        {
            this._blocoFuncoes_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._blocoFuncoes_ = node;
    }

    public PFuncao getFuncao()
    {
        return this._funcao_;
    }

    public void setFuncao(PFuncao node)
    {
        if(this._funcao_ != null)
        {
            this._funcao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._funcao_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._blocoFuncoes_)
            + toString(this._funcao_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._blocoFuncoes_ == child)
        {
            this._blocoFuncoes_ = null;
            return;
        }

        if(this._funcao_ == child)
        {
            this._funcao_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._blocoFuncoes_ == oldChild)
        {
            setBlocoFuncoes((PBlocoFuncoes) newChild);
            return;
        }

        if(this._funcao_ == oldChild)
        {
            setFuncao((PFuncao) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
