/* This file was generated by SableCC (http://www.sablecc.org/). */

package mangaba.node;

import mangaba.analysis.*;

@SuppressWarnings("nls")
public final class AVariavelVariaveisFuncao extends PVariaveisFuncao
{
    private PVariavelFuncao _variavelFuncao_;

    public AVariavelVariaveisFuncao()
    {
        // Constructor
    }

    public AVariavelVariaveisFuncao(
        @SuppressWarnings("hiding") PVariavelFuncao _variavelFuncao_)
    {
        // Constructor
        setVariavelFuncao(_variavelFuncao_);

    }

    @Override
    public Object clone()
    {
        return new AVariavelVariaveisFuncao(
            cloneNode(this._variavelFuncao_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVariavelVariaveisFuncao(this);
    }

    public PVariavelFuncao getVariavelFuncao()
    {
        return this._variavelFuncao_;
    }

    public void setVariavelFuncao(PVariavelFuncao node)
    {
        if(this._variavelFuncao_ != null)
        {
            this._variavelFuncao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._variavelFuncao_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._variavelFuncao_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._variavelFuncao_ == child)
        {
            this._variavelFuncao_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._variavelFuncao_ == oldChild)
        {
            setVariavelFuncao((PVariavelFuncao) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
