/* This file was generated by SableCC (http://www.sablecc.org/). */

package mangaba.node;

import mangaba.analysis.*;

@SuppressWarnings("nls")
public final class AVariavelDeclaracao extends PDeclaracao
{
    private PTipo _tipo_;
    private PBlocoVariaveis _blocoVariaveis_;

    public AVariavelDeclaracao()
    {
        // Constructor
    }

    public AVariavelDeclaracao(
        @SuppressWarnings("hiding") PTipo _tipo_,
        @SuppressWarnings("hiding") PBlocoVariaveis _blocoVariaveis_)
    {
        // Constructor
        setTipo(_tipo_);

        setBlocoVariaveis(_blocoVariaveis_);

    }

    @Override
    public Object clone()
    {
        return new AVariavelDeclaracao(
            cloneNode(this._tipo_),
            cloneNode(this._blocoVariaveis_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVariavelDeclaracao(this);
    }

    public PTipo getTipo()
    {
        return this._tipo_;
    }

    public void setTipo(PTipo node)
    {
        if(this._tipo_ != null)
        {
            this._tipo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tipo_ = node;
    }

    public PBlocoVariaveis getBlocoVariaveis()
    {
        return this._blocoVariaveis_;
    }

    public void setBlocoVariaveis(PBlocoVariaveis node)
    {
        if(this._blocoVariaveis_ != null)
        {
            this._blocoVariaveis_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._blocoVariaveis_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tipo_)
            + toString(this._blocoVariaveis_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tipo_ == child)
        {
            this._tipo_ = null;
            return;
        }

        if(this._blocoVariaveis_ == child)
        {
            this._blocoVariaveis_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tipo_ == oldChild)
        {
            setTipo((PTipo) newChild);
            return;
        }

        if(this._blocoVariaveis_ == oldChild)
        {
            setBlocoVariaveis((PBlocoVariaveis) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
