/* This file was generated by SableCC (http://www.sablecc.org/). */

package mangaba.node;

import mangaba.analysis.*;

@SuppressWarnings("nls")
public final class AVariaveisVariaveisFuncao extends PVariaveisFuncao
{
    private PVariaveisFuncao _variaveisFuncao_;
    private PVariavelFuncao _variavelFuncao_;

    public AVariaveisVariaveisFuncao()
    {
        // Constructor
    }

    public AVariaveisVariaveisFuncao(
        @SuppressWarnings("hiding") PVariaveisFuncao _variaveisFuncao_,
        @SuppressWarnings("hiding") PVariavelFuncao _variavelFuncao_)
    {
        // Constructor
        setVariaveisFuncao(_variaveisFuncao_);

        setVariavelFuncao(_variavelFuncao_);

    }

    @Override
    public Object clone()
    {
        return new AVariaveisVariaveisFuncao(
            cloneNode(this._variaveisFuncao_),
            cloneNode(this._variavelFuncao_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVariaveisVariaveisFuncao(this);
    }

    public PVariaveisFuncao getVariaveisFuncao()
    {
        return this._variaveisFuncao_;
    }

    public void setVariaveisFuncao(PVariaveisFuncao node)
    {
        if(this._variaveisFuncao_ != null)
        {
            this._variaveisFuncao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._variaveisFuncao_ = node;
    }

    public PVariavelFuncao getVariavelFuncao()
    {
        return this._variavelFuncao_;
    }

    public void setVariavelFuncao(PVariavelFuncao node)
    {
        if(this._variavelFuncao_ != null)
        {
            this._variavelFuncao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._variavelFuncao_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._variaveisFuncao_)
            + toString(this._variavelFuncao_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._variaveisFuncao_ == child)
        {
            this._variaveisFuncao_ = null;
            return;
        }

        if(this._variavelFuncao_ == child)
        {
            this._variavelFuncao_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._variaveisFuncao_ == oldChild)
        {
            setVariaveisFuncao((PVariaveisFuncao) newChild);
            return;
        }

        if(this._variavelFuncao_ == oldChild)
        {
            setVariavelFuncao((PVariavelFuncao) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
