/* This file was generated by SableCC (http://www.sablecc.org/). */

package mangaba.node;

import mangaba.analysis.*;

@SuppressWarnings("nls")
public final class TNega extends Token
{
    public TNega()
    {
        super.setText("não");
    }

    public TNega(int line, int pos)
    {
        super.setText("não");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TNega(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTNega(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TNega text.");
    }
}
