/* This file was generated by SableCC (http://www.sablecc.org/). */

package mangaba.node;

import mangaba.analysis.*;

@SuppressWarnings("nls")
public final class TParacada extends Token
{
    public TParacada()
    {
        super.setText("para cada");
    }

    public TParacada(int line, int pos)
    {
        super.setText("para cada");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TParacada(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTParacada(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TParacada text.");
    }
}
